import test from 'node:test';
import assert from 'node:assert/strict';
import { cartView, catalogView, homeView, publicShellView } from '../src/public-views.mjs';

const row = { categoria_id: 1, categoria_nombre: 'Splash', producto_id: 4, nombre: 'Brisa', descripcion: 'Aroma fresco', imagen_url: 'https://example.test/brisa.webp', texto_alternativo: 'Brisa', precio_referencia: 50000, precio_normal_referencia: 60000, precio_desde: true, disponibilidad: 'Disponible', destacado: true };
test('catalog has one grid, an independent add action, price and textual availability', () => { const view = catalogView([row]); assert.match(view, /public-product-grid/); assert.doesNotMatch(view, /id="categoria-1"/); assert.match(view, /Desde/); assert.match(view, /En stock/); assert.match(view, /data-product-add="4"/); assert.match(view, /aria-label="Agregar Brisa al carrito"/); });
test('catalog exposes persistent filters, tags, availability and ordering', () => { const filters = { busqueda: 'brisa', categoria: 1, disponibilidades: ['en-stock'], generos: ['hombre'], clasificaciones: [], precioMinimo: '30000', precioMaximo: '', orden: 'precio-asc' }; const view = catalogView([row], [row], filters); assert.match(view, /Filtros \(5\)/); assert.match(view, /Disponibilidad/); assert.match(view, /Menor precio/); assert.match(view, /Filtros aplicados/); assert.match(view, /Quitar filtro/); });
test('home categories lead to the shared catalog query and featured data is not hidden by name', () => { assert.match(homeView([row]), /href="\/catalogo\?categoria=1"/); assert.match(homeView([{ ...row, nombre: 'prubea' }]), /prubea/); });
test('cart renders persisted lines without purchase or payment claims', () => { const view = cartView({ version: 1, items: [{ presentationId: 2, name: 'Brisa', label: '100 ml', status: 'Disponible', price: 50000, quantity: 2 }] }); assert.match(view, /Valor total de productos/); assert.match(view, /100\.000/); assert.match(view, /data-cart-quantity="2"/); assert.doesNotMatch(view, /Pagar|Compra realizada/); });
test('public shell exposes the live cart counter and navigation', () => { const view = publicShellView('<h1>Inicio</h1>', 'home', { items: [{ quantity: 2 }] }); assert.match(view, /aria-label="Carrito \(2\)"/); assert.match(view, /href="#main-content"/); });
