import { appPath } from './app-paths.mjs';
import { getCartCount, getCartTotal, getSelectedCartItems, getSelectedCartTotal } from './public-cart.mjs';
import { getCatalogFilterCount, hasCatalogFilters, parseCatalogFilters } from './public-catalog-filters.mjs';
import { paymentProofWhatsappUrl, whatsappUrl } from './public-purchase-request.mjs';
import { PAYMENT_CONFIG, paymentInstructionsAreConfigured } from './payment-config.mjs';
import { paymentStatusLabel } from './public-payment.mjs';
import { classificationLabel } from './products.js';
import { backButton, backLink } from './back-navigation.mjs';

const logoUrl = appPath('/assets/brand/esenciales-logo-horizontal.png');
const footerLogoUrl = appPath('/assets/brand/esenciales-logo-completo.png');
const instagramIconUrl = appPath('/assets/social/instagram.png');
const whatsappSocialIconUrl = appPath('/assets/social/whatsapp.png');
const instagramUrl = 'https://www.instagram.com/esenciales.24';
const whatsappContactUrl = 'https://wa.me/573174645670';
const contactEmail = 'essentialsformen0122@gmail.com';
const homeAssets = {
  hero: appPath('/assets/home/hero-esenciales.png'),
  cta: appPath('/assets/home/cta-piedra-oscura.png'),
};
const escapeHtml = (value = '') => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;');
const money = (value) => new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 }).format(value).replace(/\s|COP/g, '');
const productsFromRows = (rows = []) => rows.filter((row) => row.producto_id != null);
const categoriesFromRows = (rows = []) => [...new Map(rows.map((row) => [row.categoria_id, { id: row.categoria_id, nombre: row.categoria_nombre }])).values()];
const statusClass = (status = '') => ({ Disponible: 'available', 'Bajo pedido': 'under-order', Agotado: 'sold-out', 'No disponible': 'unavailable' }[status] || 'neutral');
const statusLabel = (status = '') => status === 'Disponible' ? 'En stock' : status;
const arrowIcon = '<svg aria-hidden="true" viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M5 12h14M13 6l6 6-6 6"/></svg>';
const plusIcon = '<svg aria-hidden="true" viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 5v14M5 12h14"/></svg>';
const leafIcon = '<svg aria-hidden="true" viewBox="0 0 32 32" width="32" height="32" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M27 5C15 5 6 11 6 22c0 3 2 5 5 5C22 27 27 17 27 5Z"/><path d="M5 28c4-6 9-10 17-14"/></svg>';
const diamondIcon = '<svg aria-hidden="true" viewBox="0 0 32 32" width="32" height="32" fill="none" stroke="currentColor" stroke-width="1.5"><path d="m5 12 5-6h12l5 6-11 15L5 12Z"/><path d="M5 12h22M10 6l6 21M22 6l-6 21"/></svg>';
const sparklesIcon = '<svg aria-hidden="true" viewBox="0 0 32 32" width="32" height="32" fill="none" stroke="currentColor" stroke-width="1.5"><path d="m16 4 1.8 6.2L24 12l-6.2 1.8L16 20l-1.8-6.2L8 12l6.2-1.8L16 4ZM25 19l.9 3.1L29 23l-3.1.9L25 27l-.9-3.1L21 23l3.1-.9L25 19ZM7 20l.7 2.3L10 23l-2.3.7L7 26l-.7-2.3L4 23l2.3-.7L7 20Z"/></svg>';
const closeIcon = '<svg aria-hidden="true" viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="m6 6 12 12M18 6 6 18"/></svg>';
const menuIcon = '<svg aria-hidden="true" viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 6h16M4 12h16M4 18h16"/></svg>';
const copyIcon = '<svg aria-hidden="true" viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="8" y="8" width="11" height="11" rx="2"/><path d="M16 8V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2"/></svg>';
const trashIcon = '<svg aria-hidden="true" viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M4 7h16M10 11v6M14 11v6M9 7l1-3h4l1 3M6 7l1 13h10l1-13"/></svg>';
const whatsappIcon = '<svg aria-hidden="true" viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 11.5a8 8 0 0 1-11.8 7L4 20l1.5-4.1A8 8 0 1 1 20 11.5Z"/><path d="M9.3 8.4c.2-.5.4-.5.7-.5h.4c.2 0 .4.1.5.4l.7 1.6c.1.2.1.4 0 .6l-.4.6c.6 1.2 1.5 2.1 2.7 2.7l.6-.4c.2-.1.4-.1.6 0l1.6.7c.3.1.4.3.4.5v.4c0 .3 0 .5-.5.7-.6.2-1.6.1-2.7-.4-1.6-.7-3.1-2.2-3.8-3.8-.5-1.1-.6-2.1-.4-2.7Z"/></svg>';
const emailIcon = '<svg aria-hidden="true" viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/></svg>';
const locationIcon = '<svg aria-hidden="true" viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></svg>';
const footerChevron = '<svg aria-hidden="true" viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2"><path d="m6 9 6 6 6-6"/></svg>';
const cartIcon = '<svg aria-hidden="true" viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="9" cy="20" r="1"/><circle cx="19" cy="20" r="1"/><path d="M2 3h2l2.4 12h13l2-9H5"/></svg>';

function imageView(product) {
  const fallback = '<p class="public-image-fallback" data-public-image-fallback>Imagen no disponible</p>';
  return !product.imagen_url ? `<div class="public-product-image">${fallback}</div>` : `<div class="public-product-image"><img data-public-image src="${escapeHtml(product.imagen_url)}" alt="${escapeHtml(product.texto_alternativo || product.nombre || '')}" loading="lazy"><p class="public-image-fallback" data-public-image-fallback hidden>Imagen no disponible</p></div>`;
}

function productCardView(product, featured = false) {
  const price = product.precio_desde ? `Desde ${money(product.precio_referencia)}` : money(product.precio_referencia);
  const normal = Number(product.precio_normal_referencia) > Number(product.precio_referencia) ? `<s class="public-product-card__normal-price">${money(product.precio_normal_referencia)}</s>` : '';
  const unavailable = ['Agotado', 'No disponible'].includes(product.disponibilidad);
  return `<article class="public-product-card${featured ? ' public-product-card--featured' : ''}">
    <a class="public-product-card__image-link" href="${appPath(`/producto/${Number(product.producto_id)}`)}">${imageView(product)}<span class="catalog-status catalog-status--${statusClass(product.disponibilidad)}">${escapeHtml(statusLabel(product.disponibilidad))}</span></a>
    <div class="public-product-card__content"><p class="public-product-card__category">${escapeHtml(product.categoria_nombre)}</p><h3><a href="${appPath(`/producto/${Number(product.producto_id)}`)}">${escapeHtml(product.nombre)}</a></h3><p class="public-product-card__description">${escapeHtml(product.descripcion || '')}</p><div class="public-product-card__footer"><p class="public-product-card__price">${price} ${normal}</p><button class="public-add-button" type="button" data-product-add="${Number(product.producto_id)}" aria-label="Agregar ${escapeHtml(product.nombre)} al carrito" ${unavailable ? 'disabled aria-describedby="product-unavailable"' : ''}>${plusIcon}</button></div>${unavailable ? '<span id="product-unavailable" class="visually-hidden">Producto no disponible para agregar al carrito.</span>' : ''}</div>
  </article>`;
}

function editorialCategoriesView() {
  const categories = [
    ['Femeninas', 'Elegancia en cada nota', 'femenino.jpg', '/catalogo?genero=mujer'],
    ['Masculinas', 'Carácter que deja huella', 'masculino.jpg', '/catalogo?genero=hombre'],
    ['Unisex', 'Aromas sin límites', 'unisex.jpg', '/catalogo?genero=unisex'],
    ['Inspirados', 'Grandes aromas, más cerca de ti', 'inspirados.jpg', '/catalogo?clasificacion=inspiracion'],
  ];
  return categories.map(([title, subtitle, image, href]) => `<a class="editorial-category-card" href="${appPath(href)}" style="--category-image: url('${appPath(`/assets/categories/${image}`)}')"><span><strong>${title}</strong><small>${subtitle}</small></span>${arrowIcon}</a>`).join('');
}

export function legalModalView(documentName) {
  if (!documentName) return '';
  const documents = {
    terms: { title: 'Términos y condiciones', url: appPath('/legal/terminos-v2.html') },
    policy: { title: 'Política de tratamiento de datos', url: appPath('/legal/politica-datos-v2.html') },
  };
  const document = documents[documentName];
  if (!document) return '';
  const externalIcon = '<svg aria-hidden="true" viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M14 4h6v6M20 4l-9 9"/><path d="M19 13v5a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2h5"/></svg>';
  return `<section class="public-legal-modal" data-legal-modal-dialog role="dialog" aria-modal="true" aria-labelledby="legal-modal-title"><div class="public-legal-modal__panel"><header><a class="icon-button" href="${document.url}" target="_blank" rel="noopener noreferrer" aria-label="Abrir ${document.title} en una nueva pestaña" title="Abrir en una nueva pestaña">${externalIcon}</a><h2 id="legal-modal-title">${document.title}</h2><button class="icon-button" type="button" data-legal-close aria-label="Cerrar ${document.title}" title="Cerrar">×</button></header><iframe src="${document.url}" title="${document.title}"></iframe></div></section>`;
}

function footerSection(title, content) {
  return `<details class="public-footer__section" data-footer-section><summary>${title}${footerChevron}</summary><div class="public-footer__section-content">${content}</div></details>`;
}

function publicFooterView() {
  const socials = `<div class="public-footer__socials"><a href="${instagramUrl}" target="_blank" rel="noopener noreferrer" aria-label="Instagram de ESENCIALES"><img src="${instagramIconUrl}" alt=""></a><a href="${whatsappContactUrl}" target="_blank" rel="noopener noreferrer" aria-label="WhatsApp de ESENCIALES"><img src="${whatsappSocialIconUrl}" alt=""></a></div>`;
  const links = `<nav aria-label="Enlaces del pie de página"><a href="${appPath('/')}">Inicio</a><a href="${appPath('/catalogo')}">Catálogo</a></nav>`;
  const contact = `<address><a href="${whatsappContactUrl}" target="_blank" rel="noopener noreferrer">${whatsappIcon}<span>+57 317 464 5670</span></a><a href="mailto:${contactEmail}">${emailIcon}<span>${contactEmail}</span></a><p>${locationIcon}<span>Cali, Colombia</span></p></address>`;
  const information = `<nav aria-label="Información legal"><button type="button" data-legal-modal="terms">Términos y condiciones</button><button type="button" data-legal-modal="policy">Política de tratamiento de datos</button><a href="${appPath('/admin')}">Administración</a></nav>`;
  return `<footer class="public-footer"><div class="public-footer__inner"><div class="public-footer__content"><section class="public-footer__brand"><img src="${footerLogoUrl}" alt="ESENCIALES">${socials}</section>${footerSection('Enlaces', links)}${footerSection('Contáctanos', contact)}${footerSection('Información', information)}</div><div class="public-footer__bottom"><span>© 2026 ESENCIALES. Todos los derechos reservados.</span><span>Desarrollado con <span aria-label="amor">♥</span> para los amantes de las fragancias.</span></div></div></footer>`;
}

function publicNavigationLinks(currentRoute) {
  const active = (route) => currentRoute === route ? ' aria-current="page"' : '';
  return `<a href="${appPath('/')}"${active('home')}>Inicio</a><a href="${appPath('/catalogo')}"${active('catalog')}>Catálogo</a>`;
}

export function mobileMenuDrawerView(currentRoute = 'home') {
  return `<section class="public-mobile-drawer" data-mobile-menu-drawer id="mobile-menu-drawer" aria-label="Menú de navegación"><div class="public-mobile-drawer__backdrop" data-mobile-menu-close></div><aside class="public-mobile-drawer__panel" role="dialog" aria-modal="true" aria-label="Menú de navegación"><header><img src="${escapeHtml(logoUrl)}" alt="ESENCIALES"><button class="icon-button" type="button" data-mobile-menu-close aria-label="Cerrar menú" title="Cerrar menú">${closeIcon}</button></header><nav aria-label="Navegación móvil">${publicNavigationLinks(currentRoute)}</nav></aside></section>`;
}

export function publicShellView(content, currentRoute = 'home', cart = { items: [] }, modal = '', drawer = '') {
  const count = getCartCount(cart);
  return `<a class="skip-link" href="#main-content">Saltar al contenido</a><header class="public-header"><div class="public-header__inner"><button class="public-mobile-menu" type="button" data-mobile-menu-toggle aria-label="Abrir menú" aria-expanded="false" aria-controls="mobile-menu-drawer">${menuIcon}</button><a class="public-brand" href="${appPath('/')}" aria-label="Inicio"><img src="${escapeHtml(logoUrl)}" alt="ESENCIALES"></a><nav class="public-navigation" aria-label="Principal">${publicNavigationLinks(currentRoute)}</nav><button class="public-cart-link" type="button" data-cart-drawer-open aria-label="Abrir carrito (${count})" aria-haspopup="dialog"><svg aria-hidden="true" viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="9" cy="20" r="1"/><circle cx="19" cy="20" r="1"/><path d="M2 3h2l2.4 12h13l2-9H5"/></svg><span class="public-cart-link__count" aria-hidden="true">${count}</span></button></div></header><main class="public-main" id="main-content">${content}</main>${publicFooterView()}${drawer}${modal}<div class="public-live-region" role="status" aria-live="polite" aria-atomic="true"></div>`;
}

function homeViewMarkup(rows = []) {
  const products = productsFromRows(rows);
  const featured = products.filter((product) => product.destacado);
  const quality = [['Originales', 'Fragancias originales seleccionadas para quienes buscan autenticidad, presentación y la experiencia de la marca.', 'Calidad · Autenticidad · Confianza', leafIcon], ['Calidad 1.1', 'Fragancias inspiradas en perfumes reconocidos, elaboradas buscando una excelente similitud aromática, buena fijación y una experiencia de alta calidad.', '40% de concentración · Alta fijación · Excelente relación calidad-precio', diamondIcon], ['Inspirados', 'Aromas inspirados en diferentes estilos y familias olfativas, ideales para descubrir nuevas fragancias y encontrar tu próximo favorito.', 'Variedad · Personalidad · Precio accesible', sparklesIcon]];
  const steps = [['1', 'Explora', 'Descubre las fragancias y opciones disponibles.'], ['2', 'Elige', 'Selecciona la presentación y cantidad que deseas solicitar.'], ['3', 'Solicita', 'Déjanos tus datos y registra tu solicitud. Luego coordinamos contigo la disponibilidad y entrega.']];
  return `<section class="public-hero" aria-labelledby="home-title" style="--hero-image: url('${homeAssets.hero}')"><div class="public-hero__content"><h1 id="home-title">Tu aroma, siempre contigo.</h1><p>Explora lociones, perfumes y opciones de cuidado personal para cada estilo y ocasión.</p><a class="primary-button public-hero__action" href="${appPath('/catalogo')}">Ver catálogo ${arrowIcon}</a></div></section><section class="public-categories" aria-labelledby="categories-title"><div class="public-section-label"><p>Nuestras categorías</p><h2 id="categories-title">Explora por tipo de fragancia</h2></div><nav class="editorial-category-grid" aria-label="Categorías">${editorialCategoriesView()}</nav></section>${featured.length ? `<section class="public-section public-featured" aria-labelledby="featured-title"><div class="public-section__heading"><div><p class="public-section-label">Productos destacados</p><h2 id="featured-title">Fragancias que te inspiran</h2></div><a href="${appPath('/catalogo')}">Ver catálogo completo ${arrowIcon}</a></div><div class="public-product-grid">${featured.map((product) => productCardView(product, true)).join('')}</div></section>` : ''}<section class="home-quality" aria-labelledby="quality-title"><div class="home-section-intro"><p>Calidad y transparencia</p><h2 id="quality-title">Encuentra tu aroma ideal</h2></div><div class="quality-grid">${quality.map(([title, description, benefits, icon]) => `<article class="quality-card"><span class="quality-card__icon">${icon}</span><h3>${title}</h3><p>${description}</p><strong>${benefits}</strong></article>`).join('')}</div></section><section class="home-identity" aria-labelledby="identity-title" style="--identity-image: url('${homeAssets.cta}')"><div class="home-identity__content"><p>Sobre ESENCIALES</p><h2 id="identity-title">Tu aroma. Tu esencia.</h2><p>En Esenciales creemos que un perfume es mucho más que un aroma: es parte de tu identidad.</p><p>Nacimos con el propósito de acercarte a fragancias de diferentes estilos y categorías, ofreciéndote opciones para encontrar ese aroma que se siente como tú.</p><strong>Tu aroma. Tu esencia.</strong></div></section><section class="home-process" aria-labelledby="process-title"><div class="home-section-intro"><p>Proceso simple</p><h2 id="process-title">Compra tu perfume en pocos pasos</h2></div><div class="process-grid">${steps.map(([number, title, description]) => `<article><span>${number}</span><div><h3>${title}</h3><p>${description}</p></div></article>`).join('')}</div></section>`;
}

const filterChoices = { disponibilidades: [['en-stock', 'En stock'], ['bajo-pedido', 'Bajo pedido'], ['agotado', 'Agotado'], ['no-disponible', 'No disponible']], generos: [['hombre', 'Hombre'], ['mujer', 'Mujer'], ['unisex', 'Unisex']], clasificaciones: [['original', 'Original'], ['uno_a_uno', '1.1'], ['inspiracion', 'Inspiración']] };
const fieldTitle = { disponibilidades: 'Disponibilidad', generos: 'Género', clasificaciones: 'Clasificación' };

function choicesView(filters, field) { return `<fieldset><legend>${fieldTitle[field]}</legend>${filterChoices[field].map(([value, label]) => `<label><input type="checkbox" name="${field}" value="${value}" ${filters[field].includes(value) ? 'checked' : ''}>${label}</label>`).join('')}</fieldset>`; }
function categoryChoicesView(categories, filters) { return `<fieldset><legend>Categoría</legend>${categories.map((category) => `<label><input type="checkbox" name="categoria" value="${category.id}" ${String(category.id) === String(filters.categoria) ? 'checked' : ''}>${escapeHtml(category.nombre)}</label>`).join('') || '<p class="field-help">No hay categorías disponibles.</p>'}</fieldset>`; }
function filterTags(filters, categories) {
  const tags = [];
  if (filters.busqueda) tags.push(['busqueda', '', `Búsqueda: ${filters.busqueda}`]);
  if (filters.categoria) tags.push(['categoria', '', `Categoría: ${categories.find((item) => item.id === filters.categoria)?.nombre || filters.categoria}`]);
  ['disponibilidades', 'generos', 'clasificaciones'].forEach((field) => filters[field].forEach((value) => tags.push([field, value, `${fieldTitle[field]}: ${filterChoices[field].find(([key]) => key === value)?.[1] || value}`])));
  if (filters.precioMinimo) tags.push(['precioMinimo', '', `Desde ${money(filters.precioMinimo)}`]);
  if (filters.precioMaximo) tags.push(['precioMaximo', '', `Hasta ${money(filters.precioMaximo)}`]);
  return tags.length ? `<ul class="catalog-filter-tags" aria-label="Filtros aplicados">${tags.map(([field, value, label]) => `<li>${escapeHtml(label)} <button type="button" data-filter-remove="${field}" data-filter-value="${value}" aria-label="Quitar filtro ${escapeHtml(label)}">×</button></li>`).join('')}</ul>` : '';
}
function catalogControls(categories, filters, state) {
  const count = getCatalogFilterCount(filters);
  const searchIcon = '<svg aria-hidden="true" viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="11" cy="11" r="6"/><path d="m16 16 4 4"/></svg>';
  const filterIcon = '<svg aria-hidden="true" viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 6h16M7 12h10m-7 6h4"/></svg>';
  const resetIcon = '<svg aria-hidden="true" viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M20 11a8 8 0 1 0-2.3 5.7"/><path d="M20 4v7h-7"/></svg>';
  const panel = state.panelOpen ? `<div class="catalog-filter-backdrop" data-filter-close></div><aside class="catalog-filter-panel is-open" data-filter-panel aria-label="Filtros de catálogo"><header class="catalog-filter-panel__heading"><h2>Filtros</h2><button type="button" class="icon-button" data-filter-close aria-label="Cerrar filtros">${closeIcon}</button></header><div class="catalog-filter-panel__body">${categoryChoicesView(categories, filters)}${choicesView(filters, 'disponibilidades')}${choicesView(filters, 'generos')}${choicesView(filters, 'clasificaciones')}<div class="catalog-price-fields"><label>Precio mínimo<input name="precioMinimo" inputmode="numeric" value="${escapeHtml(filters.precioMinimo)}"></label><label>Precio máximo<input name="precioMaximo" inputmode="numeric" value="${escapeHtml(filters.precioMaximo)}"></label></div>${state.validation ? `<p class="message message--error" role="alert">${escapeHtml(state.validation)}</p>` : ''}</div><footer class="catalog-filter-panel__actions"><button class="primary-button" type="submit">Aplicar filtros</button><button class="secondary-button" type="button" data-clear-filters>Limpiar filtros</button></footer></aside>` : '';
  return `<form class="catalog-filters" data-catalog-form role="search"><div class="catalog-toolbar"><label class="visually-hidden" for="catalog-search">Buscar por nombre</label><div class="catalog-search">${searchIcon}<input id="catalog-search" name="busqueda" type="search" placeholder="Buscar por nombre" value="${escapeHtml(filters.busqueda)}" autocomplete="off">${filters.busqueda ? '<button type="button" class="catalog-search__clear" data-clear-search aria-label="Borrar búsqueda">×</button>' : ''}</div><div class="catalog-toolbar__actions"><button class="secondary-button catalog-filters-toggle" type="button" data-filter-toggle aria-expanded="${Boolean(state.panelOpen)}">${filterIcon}<span>Filtros${count ? ` (${count})` : ''}</span></button>${hasCatalogFilters(filters) ? `<button type="button" class="catalog-clear" data-clear-filters>${resetIcon}<span>Limpiar filtros</span></button>` : ''}</div></div>${panel}</form>${filterTags(filters, categories)}`;
}

export function homeView(rows = []) {
  return homeViewMarkup(rows).replace('<strong>Tu aroma. Tu esencia.</strong>', '');
}

export function catalogView(rows = [], filteredRows = rows, filters = parseCatalogFilters(''), state = {}) {
  filters = { disponibilidades: [], orden: 'destacados', ...filters }; const products = productsFromRows(filteredRows); const categories = categoriesFromRows(rows); const controls = catalogControls(categories, filters, state); const heading = '<div class="public-page-heading"><h1>Catálogo</h1><p>Explora productos, precios y disponibilidad.</p></div>';
  if (state.loading) return `${heading}${controls}<p class="public-loading" role="status">Cargando resultados...</p>${loadingView('Cargando resultados...')}`;
  if (state.error) return `${heading}${controls}${errorView(state.error, '/catalogo')}`;
  if (!productsFromRows(rows).length) return `${heading}${controls}<section class="public-empty-state"><h2>El catálogo está vacío</h2><p>Aún no hay productos publicables.</p></section>`;
  if (!products.length) return `${heading}${controls}<section class="public-empty-state public-empty-state--no-results"><div class="public-empty-state__icon" aria-hidden="true"><svg viewBox="0 0 24 24" width="32" height="32" fill="none" stroke="currentColor" stroke-width="1.4"><circle cx="10.5" cy="10.5" r="5.5"/><path d="m15 15 4 4M8.5 10.5h4m-2-2v4"/></svg></div><h2>No encontramos resultados con estos criterios</h2><p>Intenta ajustando los términos de búsqueda o eliminando los filtros seleccionados para explorar el catálogo completo de ESENCIALES.</p><button type="button" class="primary-button" data-clear-filters>Restablecer y ver todo <span aria-hidden="true">→</span></button></section>`;
  return `${heading}${controls}<p class="catalog-result-count" role="status">${products.length} ${products.length === 1 ? 'producto' : 'productos'}</p><div class="public-product-grid">${products.map(productCardView).join('')}</div>`;
}

function presentationPrice(presentation) { return presentation.precio_promocional ? `<span class="presentation-price__current">${money(presentation.precio_promocional)}</span> <s class="presentation-price__normal">${money(presentation.precio_normal)}</s>` : `<span class="presentation-price__current">${money(presentation.precio_normal)}</span>`; }
function cartQuantityControl(item, disabled = false) {
  const label = `cantidad de ${item.name}`;
  return `<div class="quantity-control quantity-control--input" role="group" aria-label="${escapeHtml(label)}"><button type="button" data-cart-quantity-change="${item.presentationId}" data-cart-quantity-step="-1" aria-label="Disminuir ${escapeHtml(label)}" ${disabled || item.quantity <= 1 ? 'disabled' : ''}>−</button><input type="number" inputmode="numeric" min="1" max="${Number(item.maxQuantity) || 1}" value="${item.quantity}" data-cart-quantity="${item.presentationId}" aria-label="${escapeHtml(label)}" ${disabled ? 'disabled' : ''}><button type="button" data-cart-quantity-change="${item.presentationId}" data-cart-quantity-step="1" aria-label="Aumentar ${escapeHtml(label)}" ${disabled || item.quantity >= Number(item.maxQuantity) ? 'disabled' : ''}>+</button></div>`;
}
function cartImageView(item) {
  const fallback = '<p class="public-image-fallback" data-public-image-fallback>Imagen no disponible</p>';
  return !item.imageUrl ? `<div class="public-cart-item__image">${fallback}</div>` : `<div class="public-cart-item__image"><img data-public-image src="${escapeHtml(item.imageUrl)}" alt="${escapeHtml(item.imageAlt || item.name || '')}" loading="lazy"><p class="public-image-fallback" data-public-image-fallback hidden>Imagen no disponible</p></div>`;
}
function metadata(product) { const fields = [['Género', product.genero], ['Familia olfativa', product.familia_olfativa], ['Clasificación', product.clasificacion ? classificationLabel(product.clasificacion) : null]].filter(([, value]) => value); return fields.length ? `<dl class="public-product-metadata">${fields.map(([label, value]) => `<div><dt>${label}</dt><dd>${escapeHtml(value)}</dd></div>`).join('')}</dl>` : ''; }
function productImages(product) {
  const images = Array.isArray(product.imagenes) ? product.imagenes : [];
  const fallback = product.imagen_url ? [{ url: product.imagen_url, texto_alternativo: product.texto_alternativo }] : [];
  return [...images, ...fallback].filter((image) => image?.url).filter((image, index, collection) => collection.findIndex((current) => current.url === image.url) === index);
}
function productGalleryView(product) {
  const images = productImages(product);
  const fallback = 'Imagen no disponible';
  if (!images.length) return `<div class="public-product-gallery public-product-gallery--single"><div class="public-product-image"><p class="public-image-fallback" data-public-image-fallback>${fallback}</p></div></div>`;
  const [main] = images;
  const thumbnails = images.length > 1 ? `<div class="public-product-gallery__thumbnails" aria-label="Imágenes del producto">${images.map((image, index) => `<button type="button" data-product-gallery-image data-gallery-url="${escapeHtml(image.url)}" data-gallery-alt="${escapeHtml(image.texto_alternativo || product.nombre || '')}" aria-label="Ver imagen ${index + 1} de ${images.length}" aria-pressed="${index === 0}"><img src="${escapeHtml(image.url)}" alt="" loading="lazy"></button>`).join('')}</div>` : '';
  return `<div class="public-product-gallery${images.length === 1 ? ' public-product-gallery--single' : ''}">${thumbnails}<div class="public-product-image"><img data-public-image src="${escapeHtml(main.url)}" alt="${escapeHtml(main.texto_alternativo || product.nombre || '')}"><p class="public-image-fallback" data-public-image-fallback hidden>${fallback}</p></div></div>`;
}
function detailAvailability(presentation) {
  if (presentation.estado === 'Disponible') return '';
  if (presentation.estado === 'Bajo pedido') return 'La disponibilidad se confirma directamente con ESENCIALES.';
  return 'Esta presentación no admite solicitudes.';
}
function detailQuantityControl(product, maximum) {
  const label = `cantidad de ${product.nombre}`;
  return `<div class="quantity-control quantity-control--input" role="group" aria-label="${escapeHtml(label)}"><button type="button" data-detail-quantity-change data-detail-quantity-step="-1" aria-label="Disminuir ${escapeHtml(label)}" disabled>−</button><input id="detail-quantity" name="cantidad" type="number" inputmode="numeric" min="1" max="${maximum}" step="1" value="1" data-detail-quantity aria-label="${escapeHtml(label)}"><button type="button" data-detail-quantity-change data-detail-quantity-step="1" aria-label="Aumentar ${escapeHtml(label)}" ${maximum <= 1 ? 'disabled' : ''}>+</button></div>`;
}
export function productDetailView(product) {
  if (!product) return notFoundView();
  const presentations = product.presentaciones || [];
  const firstRequestable = presentations.find((presentation) => Number(presentation.maximo_solicitable) > 0);
  const detailForm = presentations.length ? `<form class="public-product-detail__form" data-product-detail-form><fieldset class="public-presentations"><legend>Presentaciones</legend><div class="public-presentations__choices">${presentations.map((presentation) => {
    const maximum = Number(presentation.maximo_solicitable);
    const requestable = maximum > 0;
    return `<label class="public-presentation-option${requestable ? '' : ' is-unavailable'}"><input type="radio" name="presentacion" value="${Number(presentation.id)}" data-detail-presentation="${Number(presentation.id)}" data-presentation-maximum="${maximum}" ${firstRequestable?.id === presentation.id ? 'checked' : ''} ${requestable ? '' : 'disabled'}><span class="public-presentation-option__content"><strong>${escapeHtml(presentation.etiqueta)}</strong><span class="presentation-price">${presentationPrice(presentation)}</span></span></label>`;
  }).join('')}</div></fieldset>${firstRequestable ? `<div class="public-detail-purchase">${detailQuantityControl(product, Number(firstRequestable.maximo_solicitable))}<button class="primary-button" type="submit" data-product-detail-add>${cartIcon}<span>Agregar al carrito</span></button></div><div class="public-detail-availability" aria-live="polite">${presentations.map((presentation) => { const message = detailAvailability(presentation); return `<p data-detail-availability="${Number(presentation.id)}"${firstRequestable.id === presentation.id ? '' : ' hidden'}><span class="catalog-status catalog-status--${statusClass(presentation.estado)}">${escapeHtml(statusLabel(presentation.estado))}</span>${message ? `<span>${escapeHtml(message)}</span>` : ''}</p>`; }).join('')}</div>` : '<p class="public-empty">Este producto no tiene presentaciones disponibles para agregar.</p>'}</form>` : '<p class="public-empty">No hay presentaciones disponibles.</p>';
  const productMetadata = metadata(product);
  const features = productMetadata ? `<section class="public-product-features"><h2>Características</h2>${productMetadata}</section>` : '';
  return `${backLink({ href: appPath('/catalogo'), label: 'Volver al catálogo', className: 'public-back-navigation' })}<article class="public-product-detail">${productGalleryView(product)}<div class="public-product-detail__content"><p class="eyebrow">${escapeHtml(product.categoria_nombre)}</p><h1>${escapeHtml(product.nombre)}</h1>${product.marca ? `<p class="public-product-detail__brand">${escapeHtml(product.marca)}</p>` : ''}<p class="public-product-detail__description">${escapeHtml(product.descripcion)}</p>${detailForm}${features}</div></article>`;
}

export function presentationSelectorView(product) { const available = (product.presentaciones || []).filter((item) => ['Disponible', 'Bajo pedido'].includes(item.estado)); return `<section class="public-selector" data-presentation-selector role="dialog" aria-modal="true" aria-labelledby="presentation-selector-title"><div class="public-selector__heading"><h2 id="presentation-selector-title">Elige una presentación</h2><button class="icon-button" type="button" data-presentation-close aria-label="Cerrar selector">×</button></div><p>${escapeHtml(product.nombre)}</p>${available.map((item) => `<button type="button" class="public-selector__option" data-presentation-add="${Number(item.id)}"><strong>${escapeHtml(item.etiqueta)}</strong><span>${presentationPrice(item)} · ${escapeHtml(statusLabel(item.estado))}</span></button>`).join('')}</section>`; }

function requestFormView(state = {}, compact = false) {
  const form = state.form || {}; const errors = state.errors || {}; const busy = Boolean(state.busy); const review = state.priceReview;
  const fieldError = (name) => errors[name] ? `<p class="message message--error" id="request-${name}-error">${escapeHtml(errors[name])}</p>` : '';
  const describedBy = (name) => errors[name] ? `aria-describedby="request-${name}-error"` : '';
  const reviewNotice = review ? `<section class="public-request-review" role="alert"><h2>Revisa los precios actualizados</h2><p>La solicitud todavía no fue registrada. Confirma el nuevo resumen para continuar.</p><ul>${(review.lineas || []).map((line) => `<li><strong>${escapeHtml(line.producto)} · ${escapeHtml(line.presentacion)}</strong><span>Antes ${money(line.precio_esperado)} · ahora ${money(line.precio_unitario)}</span></li>`).join('')}</ul></section>` : '';
  return `<form class="public-request-form" data-request-form novalidate><div class="public-request-form__heading"><p class="eyebrow">Datos de la solicitud</p><h2>¿A quién contactamos?</h2><p>Esta es una solicitud de compra, no un pago ni una venta confirmada.</p></div>${reviewNotice}${errors.cart ? `<p class="message message--error" role="alert">${escapeHtml(errors.cart)}</p>` : ''}<div class="public-request-form__fields"><label>Nombre<input name="nombre" autocomplete="name" minlength="2" maxlength="100" value="${escapeHtml(form.nombre)}" ${describedBy('nombre')} required></label>${fieldError('nombre')}<label>Teléfono<input name="telefono" type="tel" autocomplete="tel" inputmode="tel" maxlength="30" value="${escapeHtml(form.telefono)}" ${describedBy('telefono')} required></label>${fieldError('telefono')}<label>Ciudad <span class="public-optional">Opcional</span><input name="ciudad" autocomplete="address-level2" maxlength="100" value="${escapeHtml(form.ciudad)}" ${describedBy('ciudad')}></label>${fieldError('ciudad')}<label class="public-request-form__observations">Observaciones <span class="public-optional">Opcional</span><textarea name="observaciones" maxlength="500" ${describedBy('observaciones')}>${escapeHtml(form.observaciones)}</textarea></label>${fieldError('observaciones')}</div><p class="field-help">La dirección, la entrega y el costo de envío se confirman directamente con ESENCIALES.</p><label class="public-legal-acceptance"><input name="aceptaTerminos" type="checkbox" ${form.aceptaTerminos ? 'checked' : ''}><span>He leído y acepto los <button type="button" data-legal-modal="terms">Términos y condiciones</button>.</span></label><label class="public-legal-acceptance"><input name="aceptaPoliticaDatos" type="checkbox" ${form.aceptaPoliticaDatos ? 'checked' : ''}><span>He leído y acepto la <button type="button" data-legal-modal="policy">Política de tratamiento de datos</button>.</span></label>${fieldError('aceptacion')}${state.error ? `<p class="message message--error" role="alert">${escapeHtml(state.error)}</p>` : ''}<button class="primary-button" type="submit" ${busy ? 'disabled aria-busy="true"' : ''}>${busy ? 'Registrando...' : review ? 'Confirmar nuevos precios y registrar' : 'Registrar solicitud'}</button></form>`;
}

function confirmationView(confirmation) {
  const eligible = confirmation.elegible_pago === true;
  return `<section class="public-confirmation" aria-labelledby="confirmation-title"><p class="eyebrow">ESENCIALES</p><h1 id="confirmation-title">Solicitud registrada</h1><p class="public-confirmation__code">Código de solicitud <strong>${escapeHtml(confirmation.codigo)}</strong></p><p>Tu solicitud quedó registrada como Nueva. ${eligible ? 'Puedes pagar ahora o coordinar por WhatsApp.' : 'ESENCIALES confirmará la disponibilidad antes de coordinar el pago.'}</p><ul>${confirmation.lineas.map((line) => `<li><span>${escapeHtml(line.producto)} · ${escapeHtml(line.presentacion)} × ${line.cantidad}</span><strong>${money(line.subtotal)}</strong></li>`).join('')}</ul><p class="public-confirmation__total">Valor total de productos <strong>${money(confirmation.valor_total_productos)}</strong></p><p class="payment-status payment-status--pendiente">${eligible ? 'Pago pendiente' : 'Pago por coordinar'}</p><div class="public-confirmation__actions">${eligible ? '<button class="primary-button" type="button" data-payment-start>Pagar ahora</button>' : ''}<a class="secondary-button" href="${whatsappUrl(confirmation)}" target="_blank" rel="noopener noreferrer">Continuar por WhatsApp</a><a class="secondary-button" href="${appPath('/catalogo')}">Seguir viendo productos</a><button class="link-button" type="button" data-request-new>Registrar otra solicitud</button></div></section>`;
}

function publicRequestSummaryView(request) {
  return `<section class="public-confirmation public-request-status-view" aria-labelledby="request-status-title"><p class="eyebrow">ESENCIALES</p><h1 id="request-status-title">Solicitud ${escapeHtml(request.codigo)}</h1><p class="public-confirmation__code">Estado de solicitud <strong>${escapeHtml(request.estado)}</strong></p><ul>${(request.lineas || []).map((line) => `<li><span>${escapeHtml(line.producto)} · ${escapeHtml(line.presentacion)} × ${line.cantidad}</span><strong>${money(line.subtotal)}</strong></li>`).join('')}</ul><p class="public-confirmation__total">Valor total de productos <strong>${money(request.valor_total_productos)}</strong></p><p class="payment-status payment-status--${escapeHtml(request.pago_estado)}">Pago: ${escapeHtml(paymentStatusLabel(request.pago_estado))}</p>${request.razon_rechazo ? `<p class="payment-review-note"><strong>Motivo de rechazo:</strong> ${escapeHtml(request.razon_rechazo)}</p>` : ''}</section>`;
}

function paymentProofSentView(request) {
  return `<section class="public-payment-sent" aria-label="Comprobante enviado"><p class="public-payment-sent__success" role="status"><span aria-hidden="true">✓</span><strong>Comprobante enviado</strong></p><p class="public-payment-sent__code">Solicitud <strong>${escapeHtml(request.codigo)}</strong></p><ul>${(request.lineas || []).map((line) => `<li><span>${escapeHtml(line.producto)} · ${escapeHtml(line.presentacion)} × ${line.cantidad}</span><strong>${money(line.subtotal)}</strong></li>`).join('')}</ul><p class="public-payment-sent__total"><span>Total</span><strong>${money(request.valor_total_productos)}</strong></p><p class="public-payment-sent__verification"><strong>Pendiente de verificación</strong><span>ESENCIALES revisará el comprobante antes de confirmar el pago.</span></p><div class="public-payment-sent__actions"><a class="public-whatsapp-button" href="${paymentProofWhatsappUrl(request)}" target="_blank" rel="noopener noreferrer">${whatsappIcon}<span>Continuar por WhatsApp</span></a><a href="${appPath('/catalogo')}" data-confirmation-continue>Seguir viendo productos</a></div></section>`;
}

function paymentStepView(request, state = {}) {
  const configured = paymentInstructionsAreConfigured();
  const selected = state.file;
  const status = request.pago_estado;
  if (status === 'comprobante_enviado') return paymentProofSentView(request);
  if (status === 'verificado') return `${publicRequestSummaryView(request)}<p class="payment-review-note" role="status">Tu pago fue verificado y la solicitud quedó confirmada.</p>`;
  if (!request.elegible_pago) return `${publicRequestSummaryView(request)}<p class="payment-review-note">Esta solicitud no admite pago inmediato. Si incluye productos bajo pedido o cambió la disponibilidad, coordina con ESENCIALES por WhatsApp.</p>`;
  return `<section class="public-payment-step" aria-label="Detalles de pago Bre-B"><header class="public-payment-step__summary"><p>Solicitud <strong>${escapeHtml(request.codigo)}</strong></p><p>Total a transferir <strong>${money(request.valor_total_productos)}</strong></p></header>${configured ? `<div class="payment-instructions"><img src="${escapeHtml(PAYMENT_CONFIG.qrSrc)}" alt="Código QR para pago por Bre-B"><div class="payment-key-row"><span><small>Llave</small><strong>${escapeHtml(PAYMENT_CONFIG.keyValue)}</strong></span><button type="button" class="icon-button" data-payment-copy-key="${escapeHtml(PAYMENT_CONFIG.keyValue)}" aria-label="Copiar llave Bre-B" title="Copiar llave">${copyIcon}</button></div></div>` : `<p class="payment-review-note">El pago por Bre-B estará disponible cuando ESENCIALES configure su llave y QR oficiales. Puedes continuar por WhatsApp.</p>`}<p class="field-help">El envío del comprobante no implica aprobación automática. ESENCIALES verificará la transferencia antes de confirmar el pago.</p>${configured ? `<form data-payment-proof-form class="payment-proof-form"><label class="payment-proof-file">Comprobante de pago<input name="proof" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" data-payment-proof-input><span>Seleccionar comprobante</span></label><p class="field-help">JPG, PNG, WebP o PDF. Máximo 5 MiB.</p>${selected ? `<div class="payment-file-name"><span><strong>${escapeHtml(selected.name)}</strong><small>${Math.ceil(selected.size / 1024)} KB</small></span><button type="button" class="icon-button" data-payment-proof-clear aria-label="Quitar comprobante ${escapeHtml(selected.name)}" title="Quitar comprobante">${trashIcon}</button></div>` : ''}${state.error ? `<p class="message message--error" role="alert">${escapeHtml(state.error)}</p>` : ''}<button class="primary-button" type="submit" ${state.busy || !selected ? 'disabled' : ''}>${state.busy ? 'Enviando comprobante...' : 'Enviar comprobante'}</button></form>` : ''}</section>`;
}

export function publicRequestView(request, state = {}) {
  if (!request) return errorView('No pudimos cargar la información de esta solicitud.', '/catalogo');
  if (request.pago_estado === 'comprobante_enviado') return paymentProofSentView(request);
  return state.step === 'payment' ? paymentStepView(request, state) : `${publicRequestSummaryView(request)}${request.elegible_pago ? '<button class="primary-button" type="button" data-payment-start>Pagar ahora</button>' : ''}<a class="secondary-button" href="https://wa.me/573174645670" target="_blank" rel="noopener noreferrer">Continuar por WhatsApp</a>`;
}

export function cartView(cart = { items: [] }, state = {}) {
  if (state.confirmation) return confirmationView(state.confirmation);
  if (!cart.items.length) return `<section class="public-section public-cart-empty"><p class="eyebrow">ESENCIALES</p><h1>Carrito (0)</h1><p>Tu carrito está vacío. Agrega presentaciones disponibles o bajo pedido desde el catálogo.</p><a class="primary-button" href="${appPath('/catalogo')}">Explorar catálogo</a></section>`;
  const verification = state.loading ? '<p class="public-cart__verification" role="status">Verificando disponibilidad y precios actuales...</p>' : state.error ? `<div class="public-cart__verification public-cart__verification--error"><p role="alert">${escapeHtml(state.error)}</p><button class="secondary-button" type="button" data-public-retry>Reintentar</button></div>` : state.ready === false ? '<p class="public-cart__verification public-cart__verification--warning" role="status">Corrige las líneas señaladas antes de continuar con la solicitud.</p>' : '<p class="public-cart__verification" role="status">Tu carrito está actualizado.</p>';
  const selectedItems = getSelectedCartItems(cart); const selectedTotal = getSelectedCartTotal(cart);
  const selectionNotice = selectedItems.length ? `<p class="public-cart__selection-summary">${selectedItems.length} ${selectedItems.length === 1 ? 'producto seleccionado' : 'productos seleccionados'} para esta solicitud.</p>` : '<p class="public-cart__verification public-cart__verification--warning" role="status">Selecciona al menos un producto para registrar la solicitud.</p>';
  return `<section class="public-cart"><div class="public-page-heading"><p class="eyebrow">ESENCIALES</p><h1>Revisa tu carrito</h1><p>Elige las presentaciones que deseas incluir antes de registrar la solicitud.</p></div>${verification}<div class="public-cart__layout"><div>${selectionNotice}<ul class="public-cart__items">${cart.items.map((item) => {
    const validation = item.validation; const disabled = state.loading || validation?.quantityEditable === false;
    const notice = validation?.message ? `<p class="public-cart__notice public-cart__notice--${escapeHtml(validation.state)}" role="status">${escapeHtml(validation.message)}</p>` : '';
    return `<li class="public-cart-item ${validation?.state === 'blocked' ? 'is-blocked' : ''}">${cartImageView(item)}<div class="public-cart-item__details"><label class="public-cart__select"><input type="checkbox" data-cart-select="${item.presentationId}" ${item.selected !== false ? 'checked' : ''} ${disabled ? 'disabled' : ''}><span>Incluir en esta solicitud</span></label><strong>${escapeHtml(item.name)}</strong><span>${escapeHtml(item.label)}</span><span class="catalog-status catalog-status--${statusClass(item.status)}">${escapeHtml(statusLabel(item.status))}</span><span>${money(item.price)} c/u</span>${notice}</div><div class="public-cart-item__actions">${cartQuantityControl(item, disabled)}<strong class="public-cart-item__subtotal">${money(item.price * item.quantity)}</strong><button class="icon-button public-cart-item__remove" type="button" data-cart-remove="${item.presentationId}" aria-label="Retirar ${escapeHtml(item.name)}" title="Retirar">${trashIcon}</button></div></li>`;
  }).join('')}</ul></div><aside class="public-cart__summary"><p>Valor total de productos seleccionados</p><strong class="public-cart__total">${money(selectedTotal)}</strong>${selectedItems.length !== cart.items.length ? `<p class="field-help">Total del carrito: ${money(getCartTotal(cart))}</p>` : ''}<p>Domicilio o envío se confirma posteriormente con ESENCIALES.</p><a class="secondary-button" href="${appPath('/catalogo')}">Seguir comprando</a></aside></div>${state.ready && !state.loading && !state.error && selectedItems.length ? requestFormView(state.requestState) : ''}</section>`;
}

function drawerConfirmationView(confirmation, state = {}) {
  const eligible = confirmation.elegible_pago === true;
  const continuation = eligible
    ? '<p>Puedes pagar ahora o continuar por WhatsApp para recibir asesoría.</p>'
    : '<h3>Pago por coordinar</h3><p>Tu solicitud contiene productos bajo pedido. ESENCIALES confirmará su disponibilidad antes de realizar el pago.</p>';
  return `<section class="public-drawer-confirmation"><p class="public-drawer-confirmation__success"><span aria-hidden="true">✓</span><span><strong>Tu solicitud se registró correctamente.</strong><small>Guarda este código para identificar tu solicitud.</small></span></p><div class="public-drawer-confirmation__code"><span>Código de solicitud</span><div><strong>${escapeHtml(confirmation.codigo)}</strong><button class="icon-button" type="button" data-confirmation-copy="${escapeHtml(confirmation.codigo)}" aria-label="Copiar código de solicitud" title="Copiar código de solicitud">${copyIcon}</button></div></div><section class="public-drawer-confirmation__summary" aria-labelledby="drawer-request-summary"><h3 id="drawer-request-summary">Resumen de tu solicitud</h3><ul>${confirmation.lineas.map((line) => `<li><span>${escapeHtml(line.producto)} · ${escapeHtml(line.presentacion)} × ${line.cantidad}</span><strong>${money(line.subtotal)}</strong></li>`).join('')}</ul><p class="public-drawer-confirmation__total"><span>Total</span><strong>${money(confirmation.valor_total_productos)}</strong></p></section>${eligible ? '<p class="payment-status payment-status--pendiente">Pago pendiente</p>' : ''}<section class="public-drawer-confirmation__continuation">${continuation}</section><div class="public-drawer-confirmation__actions">${eligible ? `<button class="primary-button" type="button" data-payment-start>Pagar ahora ${arrowIcon}</button>` : ''}<a class="public-whatsapp-button" href="${whatsappUrl(confirmation)}" target="_blank" rel="noopener noreferrer">${whatsappIcon}<span>Continuar por WhatsApp</span></a></div><nav class="public-drawer-confirmation__links" aria-label="Acciones secundarias"><a href="${appPath('/catalogo')}" data-confirmation-continue>Seguir viendo productos</a><span aria-hidden="true" class="public-drawer-confirmation__links-separator"></span><button class="link-button" type="button" data-request-new>Registrar otra solicitud</button></nav></section>`;
}

function drawerRequestFormView(state = {}) {
  const form = state.form || {}; const errors = state.errors || {}; const busy = Boolean(state.busy); const review = state.priceReview;
  const error = (name) => errors[name] ? `<p class="public-request-form__error" id="request-${name}-error">${escapeHtml(errors[name])}</p>` : '';
  const invalid = (name) => errors[name] ? `aria-invalid="true" aria-describedby="request-${name}-error"` : '';
  const reviewNotice = review ? `<section class="public-request-review" role="alert"><h2>Revisa los precios actualizados</h2><p>La solicitud todavía no fue registrada. Confirma el nuevo resumen para continuar.</p></section>` : '';
  return `<form class="public-request-form public-request-form--drawer" data-request-form novalidate><div class="public-request-form__heading"><h3>¿A quién contactamos?</h3><p>Esta es una solicitud de compra, no un pago ni una venta confirmada.</p></div>${reviewNotice}${errors.cart ? `<p class="public-request-form__error" role="alert">${escapeHtml(errors.cart)}</p>` : ''}<div class="public-request-form__fields"><div class="public-request-form__field"><label for="request-name">Nombre</label><input id="request-name" name="nombre" autocomplete="name" minlength="2" maxlength="100" value="${escapeHtml(form.nombre)}" ${invalid('nombre')} required>${error('nombre')}</div><div class="public-request-form__field"><label for="request-phone">Teléfono</label><input id="request-phone" name="telefono" type="tel" autocomplete="tel" inputmode="tel" maxlength="30" value="${escapeHtml(form.telefono)}" ${invalid('telefono')} required>${error('telefono')}</div><div class="public-request-form__field"><label for="request-city">Ciudad <span class="public-optional">Opcional</span></label><input id="request-city" name="ciudad" autocomplete="address-level2" maxlength="100" value="${escapeHtml(form.ciudad)}" ${invalid('ciudad')}>${error('ciudad')}</div><div class="public-request-form__field public-request-form__observations"><label for="request-notes">Observaciones <span class="public-optional">Opcional</span></label><textarea id="request-notes" name="observaciones" maxlength="500" ${invalid('observaciones')}>${escapeHtml(form.observaciones)}</textarea>${error('observaciones')}</div></div><p class="field-help">La dirección, la entrega y el costo de envío se confirman directamente con ESENCIALES.</p><div class="public-request-form__legal"><label class="public-legal-acceptance"><input name="aceptaTerminos" type="checkbox" ${form.aceptaTerminos ? 'checked' : ''} ${errors.aceptacion ? 'aria-invalid="true" aria-describedby="request-acceptance-error"' : ''}><span>He leído y acepto los <button type="button" data-legal-modal="terms">Términos y condiciones</button>.</span></label><label class="public-legal-acceptance"><input name="aceptaPoliticaDatos" type="checkbox" ${form.aceptaPoliticaDatos ? 'checked' : ''} ${errors.aceptacion ? 'aria-invalid="true" aria-describedby="request-acceptance-error"' : ''}><span>He leído y acepto la <button type="button" data-legal-modal="policy">Política de tratamiento de datos</button>.</span></label>${errors.aceptacion ? `<p class="public-request-form__error" id="request-acceptance-error">${escapeHtml(errors.aceptacion)}</p>` : ''}</div>${state.error ? `<p class="public-request-form__error" role="alert">${escapeHtml(state.error)}</p>` : ''}<button class="primary-button" type="submit" ${busy ? 'disabled aria-busy="true"' : ''}>${busy ? 'Registrando solicitud...' : 'Registrar solicitud'}</button></form>`;
}

function drawerCartItemView(item, { selectionDisabled = false, quantityDisabled = false } = {}) {
  const notice = item.validation?.message ? `<p class="public-cart__notice public-cart__notice--${escapeHtml(item.validation.state)}" role="alert">${escapeHtml(item.validation.message)}</p>` : '';
  return `<li class="public-cart-drawer__item ${item.validation?.state === 'blocked' ? 'is-blocked' : ''}"><label class="public-cart-drawer__select"><input type="checkbox" data-cart-select="${item.presentationId}" aria-label="Incluir ${escapeHtml(item.name)} en esta solicitud" ${item.selected !== false ? 'checked' : ''} ${selectionDisabled ? 'disabled' : ''}><span class="visually-hidden">Incluir ${escapeHtml(item.name)} en esta solicitud</span></label>${cartImageView(item)}<div class="public-cart-drawer__item-content"><div class="public-cart-drawer__item-top"><strong>${escapeHtml(item.name)}</strong><strong>${money(item.price * item.quantity)}</strong></div><p class="public-cart-drawer__item-meta">${escapeHtml(item.label)} <span aria-hidden="true">•</span> <span class="catalog-status catalog-status--${statusClass(item.status)}">${escapeHtml(statusLabel(item.status))}</span></p><span class="public-cart-drawer__unit-price">${money(item.price)} c/u</span>${notice}<div class="public-cart-drawer__actions">${cartQuantityControl(item, quantityDisabled)}<button class="icon-button public-cart-drawer__remove" type="button" data-cart-remove="${item.presentationId}" aria-label="Retirar ${escapeHtml(item.name)}" title="Retirar">${trashIcon}</button></div></div></li>`;
}
export function cartDrawerView(cart = { items: [] }, state = {}) {
  const drawer = typeof state === 'boolean' ? { open: state } : state;
  if (!drawer.open) return '';
  const items = cart.items || [];
  const cartState = drawer.cartState || {};
  const selectedItems = getSelectedCartItems(cart);
  const total = getSelectedCartTotal(cart);
  const verification = cartState.loading ? '<p class="public-cart__verification" role="status">Verificando disponibilidad y precios actuales...</p>' : cartState.error ? `<p class="public-cart__verification public-cart__verification--error" role="alert">${escapeHtml(cartState.error)}</p>` : cartState.ready === false ? '<p class="public-cart__verification public-cart__verification--warning" role="alert">Corrige las líneas señaladas antes de continuar con la solicitud.</p>' : '';
  const drawerError = drawer.error ? `<p class="public-cart__verification public-cart__verification--error" role="alert">${escapeHtml(drawer.error)}</p>` : '';
  const header = ['form', 'payment'].includes(drawer.step) ? `${backButton({ label: 'Volver al carrito', className: 'public-cart-drawer__back', attributes: 'data-cart-drawer-back' })}<div><h2 id="cart-drawer-title">${drawer.step === 'payment' ? 'Pago Bre-B' : 'Datos de la solicitud'}</h2></div>` : `<div><h2 id="cart-drawer-title">${drawer.step === 'confirmation' ? 'Solicitud registrada' : 'Tu carrito'}</h2></div>`;
  const selectionSummary = selectedItems.length ? `${selectedItems.length} de ${items.length} ${items.length === 1 ? 'producto seleccionado' : 'productos seleccionados'}` : 'Selecciona al menos un producto para continuar';
  const body = drawer.step === 'confirmation' && drawer.confirmation ? `<div class="public-cart-drawer__confirmation">${drawerConfirmationView(drawer.confirmation, drawer)}</div>` : drawer.step === 'payment' && drawer.paymentRequest ? `<div class="public-cart-drawer__confirmation">${paymentStepView(drawer.paymentRequest, drawer.paymentState)}</div>` : drawer.step === 'form' ? `<div class="public-cart-drawer__form"><p class="public-cart-drawer__summary">${selectedItems.length} ${selectedItems.length === 1 ? 'producto' : 'productos'} · <strong>${money(total)}</strong></p>${drawerRequestFormView(drawer.requestState)}</div>` : items.length ? `${verification}${drawerError}<ul>${items.map((item) => drawerCartItemView(item, { selectionDisabled: cartState.loading, quantityDisabled: cartState.loading || item.validation?.quantityEditable === false })).join('')}</ul><footer><p>Total <strong>${money(total)}</strong></p><p class="field-help">${selectionSummary}</p><button class="primary-button" type="button" data-cart-drawer-continue ${cartState.loading || cartState.error || cartState.ready === false || !selectedItems.length ? 'disabled' : ''}>Continuar con la solicitud</button></footer>` : `<div class="public-cart-drawer__empty">${drawerError}<p>Tu carrito está vacío.</p><button class="secondary-button" type="button" data-cart-drawer-close>Continuar explorando</button></div>`;
  return `<div class="public-cart-drawer" data-cart-drawer><div class="public-cart-drawer__backdrop" data-cart-drawer-close></div><aside class="public-cart-drawer__panel" role="dialog" aria-modal="true" aria-labelledby="cart-drawer-title"><header>${header}<button class="icon-button" type="button" data-cart-drawer-close aria-label="${drawer.step === 'confirmation' ? 'Cerrar' : 'Cerrar carrito'}" title="Cerrar">${closeIcon}</button></header>${body}</aside></div>`;
}
export function notFoundView() { return `<section class="public-section public-not-found"><h1>No encontrado</h1><p>Este producto no existe o dejó de publicarse.</p>${backLink({ href: appPath('/catalogo'), label: 'Volver al catálogo' })}</section>`; }
export function loadingView(label = 'Cargando catálogo...') { return `<p class="public-loading" role="status">${escapeHtml(label)}</p><div class="public-skeleton" aria-hidden="true"><span></span><span></span><span></span><span></span></div>`; }
export function errorView(message, retryRoute) { return `<section class="public-section public-error"><p class="message message--error" role="alert">${escapeHtml(message)}</p><button class="secondary-button" type="button" data-public-retry="${escapeHtml(retryRoute)}">Reintentar</button></section>`; }
export function renderPublicRoute(route, result = {}) { if (route.name === 'cart') return cartView(result.cart, result.cartState); if (route.name === 'request') return publicRequestView(result.data, result.paymentState); if (route.name === 'not-found') return notFoundView(); if (result.error) return errorView(result.error, route.name === 'product' ? `/producto/${route.productId}` : `/${route.name === 'catalog' ? 'catalogo' : ''}`); if (route.name === 'product') return result.data ? productDetailView(result.data) : notFoundView(); if (route.name === 'catalog') return result.catalogState ? catalogView(result.catalogState.baseRows, result.catalogState.filteredRows, result.catalogState.filters, result.catalogState) : catalogView(result.data || []); return homeView(result.data || []); }
