const money = (value) => new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 }).format(Number(value) || 0);
const dateTime = (value) => value ? new Intl.DateTimeFormat('es-CO', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—';
const escapeHtml = (value = '') => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;');
const requestStatus = (value) => ({ nueva: 'Nueva', confirmada: 'Confirmada', entregada: 'Entregada', cancelada: 'Cancelada' }[value] || 'Desconocida');
const requestTotal = (request) => (request.detalles_solicitud || []).reduce((total, line) => total + Number(line.subtotal || 0), 0);
const lineName = (line) => `${line.presentaciones?.productos?.nombre || 'Producto sin nombre'} · ${line.presentaciones?.etiqueta || 'Presentación sin nombre'}`;

function statusView(status) { return `<span class="request-status request-status--${escapeHtml(status)}">${requestStatus(status)}</span>`; }
function lineListView(lines, editable = false) {
  return `<ul class="request-lines">${lines.map((line) => `<li><div><strong>${escapeHtml(lineName(line))}</strong><span>Precio histórico: ${money(line.precio_unitario)}</span></div>${editable ? `<label>Cantidad<input type="number" name="cantidad-${line.id}" min="1" max="99" required value="${Number(line.cantidad)}" inputmode="numeric"></label><button class="danger-button" type="button" data-request-line-remove="${line.id}" ${lines.length === 1 ? 'disabled' : ''}>Retirar</button>` : `<span>Cantidad: ${Number(line.cantidad)}</span>`}<strong>${money(line.subtotal)}</strong></li>`).join('')}</ul>`;
}

function requestSummaryView(request) {
  return `<section class="request-summary" aria-label="Resumen de solicitud"><div><span>Valor total de productos</span><strong>${money(requestTotal(request))}</strong></div><p>Domicilio o envío se confirma posteriormente con ESENCIALES.</p></section>`;
}

export function purchaseRequestsView({ requests = [], allCount = requests.length, filters = {}, loading = false, error = '' } = {}) {
  if (loading) return '<section class="requests-page" aria-busy="true"><div class="inventory-skeleton"><span></span><span></span><span></span></div></section>';
  const controls = `<section class="requests-controls" aria-label="Búsqueda y filtros"><label for="requests-search"><span class="visually-hidden">Buscar por código, cliente o teléfono</span><input id="requests-search" type="search" value="${escapeHtml(filters.query)}" placeholder="Buscar por código, cliente o teléfono"></label><label for="requests-status"><span>Estado</span><select id="requests-status"><option value="">Todos los estados</option>${['nueva', 'confirmada', 'entregada', 'cancelada'].map((status) => `<option value="${status}" ${filters.status === status ? 'selected' : ''}>${requestStatus(status)}</option>`).join('')}</select></label></section>`;
  if (error) return `<section class="requests-page"><header class="requests-heading"><p>Consulta y corrige solicitudes de compra registradas.</p></header>${controls}<p class="message message--error" role="alert">${escapeHtml(error)}</p><button class="secondary-button" type="button" data-requests-retry>Reintentar</button></section>`;
  if (!requests.length) return `<section class="requests-page"><header class="requests-heading"><p>Consulta y corrige solicitudes de compra registradas.</p></header>${controls}<section class="inventory-empty"><h2>${allCount ? 'No hay solicitudes con esos filtros' : 'Aún no hay solicitudes registradas'}</h2><p>${allCount ? 'Cambia la búsqueda o el estado para ver otras solicitudes.' : 'Las solicitudes que envíen los visitantes aparecerán aquí.'}</p></section></section>`;
  const row = (request) => `<tr><td><strong>${escapeHtml(request.codigo)}</strong><small>${dateTime(request.creado_en)}</small></td><td>${escapeHtml(request.nombre_cliente)}<small>${escapeHtml(request.telefono)}</small></td><td>${money(requestTotal(request))}</td><td>${statusView(request.estado)}</td><td><button class="secondary-button" type="button" data-request-open="${request.id}">Ver detalle</button></td></tr>`;
  const card = (request) => `<li><div class="request-card__heading"><strong>${escapeHtml(request.codigo)}</strong>${statusView(request.estado)}</div><span>${escapeHtml(request.nombre_cliente)}</span><span>${escapeHtml(request.telefono)}</span><strong>${money(requestTotal(request))}</strong><small>${dateTime(request.creado_en)}</small><button class="secondary-button" type="button" data-request-open="${request.id}">Ver detalle</button></li>`;
  return `<section class="requests-page"><header class="requests-heading"><p>Consulta solicitudes registradas y corrige solo las que aún están Nuevas.</p></header>${controls}<p class="requests-result-count">${requests.length} ${requests.length === 1 ? 'solicitud' : 'solicitudes'}</p><div class="requests-table-wrap"><table class="requests-table"><thead><tr><th scope="col">Solicitud</th><th scope="col">Cliente</th><th scope="col">Total</th><th scope="col">Estado</th><th scope="col"><span class="visually-hidden">Acción</span></th></tr></thead><tbody>${requests.map(row).join('')}</tbody></table></div><ul class="requests-cards">${requests.map(card).join('')}</ul></section>`;
}

export function purchaseRequestDetailView(request, { values = {}, busy = false, dirty = false, error = '' } = {}) {
  const editable = request.estado === 'nueva';
  const formValues = { nombre_cliente: request.nombre_cliente, telefono: request.telefono, ciudad: request.ciudad || '', observaciones: request.observaciones || '', lineas: request.detalles_solicitud || [], ...values };
  const customer = editable ? `<div class="request-form__fields"><label>Nombre<input name="nombre_cliente" required minlength="2" maxlength="100" value="${escapeHtml(formValues.nombre_cliente)}"></label><label>Teléfono<input name="telefono" required minlength="7" maxlength="20" value="${escapeHtml(formValues.telefono)}"></label><label>Ciudad <span class="field-optional">Opcional</span><input name="ciudad" maxlength="100" value="${escapeHtml(formValues.ciudad)}"></label><label class="request-form__observations">Observaciones <span class="field-optional">Opcional</span><textarea name="observaciones" maxlength="500">${escapeHtml(formValues.observaciones)}</textarea></label></div>` : `<dl class="request-customer"><div><dt>Nombre</dt><dd>${escapeHtml(request.nombre_cliente)}</dd></div><div><dt>Teléfono</dt><dd>${escapeHtml(request.telefono)}</dd></div><div><dt>Ciudad</dt><dd>${escapeHtml(request.ciudad || '—')}</dd></div><div><dt>Observaciones</dt><dd>${escapeHtml(request.observaciones || '—')}</dd></div></dl>`;
  const lines = editable ? formValues.lineas : request.detalles_solicitud || [];
  const transitionDisabled = busy || dirty;
  const transitionHint = dirty ? '<p class="message message--info">Guarda o cancela los cambios antes de cambiar el estado.</p>' : '';
  const transitionActions = request.estado === 'nueva'
    ? `<button class="primary-button" type="button" data-request-transition="confirm" ${transitionDisabled ? `disabled${busy ? ' aria-busy="true"' : ''}` : ''}>${busy ? 'Procesando...' : 'Confirmar solicitud'}</button><button class="danger-button" type="button" data-request-transition="cancel" ${transitionDisabled ? 'disabled' : ''}>Cancelar solicitud</button>`
    : request.estado === 'confirmada'
      ? `<button class="primary-button" type="button" data-request-transition="deliver" ${transitionDisabled ? `disabled${busy ? ' aria-busy="true"' : ''}` : ''}>${busy ? 'Procesando...' : 'Marcar como entregada'}</button><button class="danger-button" type="button" data-request-transition="cancel" ${transitionDisabled ? 'disabled' : ''}>Cancelar solicitud</button>`
      : '';
  const actions = transitionActions ? `${transitionHint}<div class="request-form__actions">${transitionActions}</div>` : '';
  return `<section class="request-detail"><button class="link-button" type="button" data-request-back>Volver a solicitudes</button><header class="request-detail__heading"><div><p class="eyebrow">Solicitud</p><h2>${escapeHtml(request.codigo)}</h2><p>${dateTime(request.creado_en)}</p></div>${statusView(request.estado)}</header>${error ? `<p class="message message--error" role="alert">${escapeHtml(error)}</p>` : ''}${editable ? `<form id="request-edit-form" class="request-form"><p>Esta solicitud aún no descuenta inventario. Puedes corregir los datos, cantidades o retirar líneas existentes.</p>${customer}<section><h3>Productos solicitados</h3>${lineListView(lines, true)}</section>${requestSummaryView({ ...request, detalles_solicitud: lines.map((line) => ({ ...line, cantidad: Number(line.cantidad), subtotal: Number(line.cantidad) * Number(line.precio_unitario) })) })}<div class="request-form__actions"><button class="secondary-button" type="submit" data-busy-label="Guardando..." ${busy ? 'disabled aria-busy="true"' : ''}>${busy ? 'Guardando...' : 'Guardar cambios'}</button><button class="secondary-button" type="button" data-request-back ${busy ? 'disabled' : ''}>Cancelar edición</button></div>${actions}</form>` : `<section class="request-readonly">${customer}<section><h3>Productos solicitados</h3>${lineListView(lines)}</section>${requestSummaryView(request)}${actions}<p class="message message--info">Las solicitudes ${requestStatus(request.estado)} son de solo lectura.</p></section>`}</section>`;
}
