const money = (value) => new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 }).format(Number(value) || 0);
const dateTime = (value) => value ? new Intl.DateTimeFormat('es-CO', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—';
const escapeHtml = (value = '') => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;');
const requestStatus = (value) => ({ nueva: 'Nueva', confirmada: 'Confirmada', entregada: 'Entregada', cancelada: 'Cancelada' }[value] || 'Desconocida');
const requestTotal = (request) => (request.detalles_solicitud || []).reduce((total, line) => total + Number(line.subtotal || 0), 0);
const requestProductCount = (request) => (request.detalles_solicitud || []).reduce((total, line) => total + Number(line.cantidad || 0), 0);
const lineName = (line) => `${line.presentaciones?.productos?.nombre || 'Producto sin nombre'} · ${line.presentaciones?.etiqueta || 'Presentación sin nombre'}`;
const eyeIcon = '<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"/><circle cx="12" cy="12" r="2.5"/></svg>';
const backIcon = '<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M19 12H5m6-6-6 6 6 6"/></svg>';
const infoIcon = '<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="9"/><path d="M12 10v6m0-9.25v.5" stroke-linecap="round"/></svg>';
const checkIcon = '<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 4.5 4.5L19 7"/></svg>';
const closeIcon = '<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="m7 7 10 10M17 7 7 17"/></svg>';
const trashIcon = '<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M4 7h16M10 11v6M14 11v6M9 7l1-3h4l1 3M6 7l1 13h10l1-13"/></svg>';

function statusView(status) { return `<span class="request-status request-status--${escapeHtml(status)}">${requestStatus(status)}</span>`; }
function paymentFor(request) { return Array.isArray(request.pagos_solicitud) ? request.pagos_solicitud[0] : request.pagos_solicitud; }
function paymentStatusView(payment) { const label = { pendiente: 'Sin comprobante', comprobante_enviado: 'Comprobante', verificado: 'Verificado', rechazado: 'Rechazado', validado_manualmente: 'Validado manualmente' }[payment?.estado] || 'Sin comprobante'; return `<span class="payment-status payment-status--${escapeHtml(payment?.estado || 'pendiente')}">${label}</span>`; }
function paymentDetailStatusView(payment) { const label = { pendiente: 'Sin comprobante', comprobante_enviado: 'Comprobante enviado', verificado: 'Verificado', rechazado: 'Rechazado', validado_manualmente: 'Validado manualmente' }[payment?.estado] || 'Sin comprobante'; return `<span class="payment-status payment-status--${escapeHtml(payment?.estado || 'pendiente')}">${label}</span>`; }
function immediateStock(line) {
  const presentation = line.presentaciones || {};
  return presentation.modo_disponibilidad === 'venta_inmediata' && Number.isInteger(Number(presentation.stock)) ? Math.max(0, Number(presentation.stock)) : null;
}

function quantityControl(line, error = '') {
  const quantity = Number(line.cantidad);
  const label = `cantidad de ${lineName(line)}`;
  const maximum = immediateStock(line);
  const descriptionId = `request-quantity-help-${line.id}`;
  const help = maximum === null ? '' : `<small id="${descriptionId}" class="request-quantity-help${error ? ' request-quantity-help--error' : ''}" data-request-quantity-feedback="${line.id}">${escapeHtml(error || `Máx. disponible: ${maximum}`)}</small>`;
  return `<div class="quantity-control quantity-control--input request-quantity-control" role="group" aria-label="${escapeHtml(label)}"><button type="button" data-request-quantity-change="${line.id}" data-request-quantity-step="-1" aria-label="Disminuir ${escapeHtml(label)}" ${quantity <= 1 ? 'disabled' : ''}>−</button><input type="number" name="cantidad-${line.id}" min="1" max="99" required value="${quantity}" inputmode="numeric" data-request-quantity-input="${line.id}" aria-label="${escapeHtml(label)}" ${help ? `aria-describedby="${descriptionId}" aria-invalid="${Boolean(error)}"` : ''}><button type="button" data-request-quantity-change="${line.id}" data-request-quantity-step="1" aria-label="Aumentar ${escapeHtml(label)}" ${quantity >= 99 || (maximum !== null && quantity >= maximum) ? 'disabled' : ''}>+</button></div>${help}`;
}

function lineListView(lines, editable = false, quantityErrors = {}) {
  const line = (item) => `<li class="request-line"><div class="request-line__product"><strong>${escapeHtml(lineName(item))}</strong></div><div class="request-line__price"><span>Precio histórico</span><strong>${money(item.precio_unitario)}</strong></div><div class="request-line__quantity"><span>Cantidad</span>${editable ? quantityControl(item, quantityErrors[item.id]) : `<strong>${Number(item.cantidad)}</strong>`}</div><div class="request-line__subtotal"><span>Subtotal</span><strong>${money(editable ? Number(item.cantidad) * Number(item.precio_unitario) : item.subtotal)}</strong></div>${editable ? `<div class="request-line__action"><button class="request-line-remove" type="button" data-request-line-remove="${item.id}" aria-label="Retirar producto ${escapeHtml(lineName(item))}" title="Retirar producto" ${lines.length === 1 ? 'disabled' : ''}>${trashIcon}</button></div>` : ''}</li>`;
  const columns = `<div class="request-lines__columns" aria-hidden="true"><span>Producto</span><span>Precio</span><span>Cantidad</span><span>Subtotal</span>${editable ? '<span>Acción</span>' : ''}</div>`;
  return `${columns}<ul class="request-lines">${lines.map(line).join('')}</ul>`;
}

function requestSummaryView(request) {
  return `<section class="request-summary" aria-labelledby="request-summary-title"><h3 id="request-summary-title">Resumen</h3><div><span>Valor de productos</span><strong>${money(requestTotal(request))}</strong></div><p>Domicilio o envío se confirma posteriormente con ESENCIALES.</p></section>`;
}

export function purchaseRequestsView({ requests = [], allCount = requests.length, filters = {}, loading = false, error = '' } = {}) {
  if (loading) return '<section class="requests-page" aria-busy="true"><div class="inventory-skeleton"><span></span><span></span><span></span></div></section>';
  const controls = `<section class="requests-controls" aria-label="Búsqueda y filtros"><label for="requests-search"><span class="visually-hidden">Buscar por código, cliente o teléfono</span><input id="requests-search" type="search" value="${escapeHtml(filters.query)}" placeholder="Buscar por código, cliente o teléfono"></label><label for="requests-status"><span>Estado</span><select id="requests-status"><option value="">Todos los estados</option>${['nueva', 'confirmada', 'entregada', 'cancelada'].map((status) => `<option value="${status}" ${filters.status === status ? 'selected' : ''}>${requestStatus(status)}</option>`).join('')}</select></label></section>`;
  if (error) return `<section class="requests-page"><header class="requests-heading"><p>Consulta y corrige solicitudes de compra registradas.</p></header>${controls}<p class="message message--error" role="alert">${escapeHtml(error)}</p><button class="secondary-button" type="button" data-requests-retry>Reintentar</button></section>`;
  if (!requests.length) return `<section class="requests-page"><header class="requests-heading"><p>Consulta y corrige solicitudes de compra registradas.</p></header>${controls}<section class="inventory-empty"><h2>${allCount ? 'No hay solicitudes con esos filtros' : 'Aún no hay solicitudes registradas'}</h2><p>${allCount ? 'Cambia la búsqueda o el estado para ver otras solicitudes.' : 'Las solicitudes que envíen los visitantes aparecerán aquí.'}</p></section></section>`;
  const detailButton = (request) => `<button class="request-detail-button" type="button" data-request-open="${request.id}" aria-label="Ver detalle de la solicitud ${escapeHtml(request.codigo)}" title="Ver detalle">${eyeIcon}</button>`;
  const productLabel = (request) => `${requestProductCount(request)} ${requestProductCount(request) === 1 ? 'producto' : 'productos'}`;
  const row = (request) => `<tr class="request-row" data-request-row="${request.id}"><td><strong>${escapeHtml(request.codigo)}</strong><small>${dateTime(request.creado_en)}</small></td><td><strong>${escapeHtml(request.nombre_cliente)}</strong><small>${escapeHtml(request.telefono)}</small></td><td class="request-products">${requestProductCount(request)}</td><td class="request-total">${money(requestTotal(request))}</td><td>${statusView(request.estado)}</td><td>${paymentStatusView(paymentFor(request))}</td><td class="request-action">${detailButton(request)}</td></tr>`;
  const card = (request) => `<li class="request-card"><div class="request-card__heading"><strong>${escapeHtml(request.codigo)}</strong>${statusView(request.estado)}</div><small class="request-card__date">${dateTime(request.creado_en)}</small><div class="request-card__customer"><strong>${escapeHtml(request.nombre_cliente)}</strong><small>${escapeHtml(request.telefono)}</small></div><div class="request-card__summary"><span>${productLabel(request)}</span><strong>${money(requestTotal(request))}</strong></div><div class="request-card__footer"><div class="request-card__payment"><span>Pago:</span>${paymentStatusView(paymentFor(request))}</div><div class="request-card__action">${detailButton(request)}</div></div></li>`;
  return `<section class="requests-page"><header class="requests-heading"><p>Consulta solicitudes registradas y corrige solo las que aún están Nuevas.</p></header>${controls}<p class="requests-result-count">${requests.length} ${requests.length === 1 ? 'solicitud encontrada' : 'solicitudes encontradas'}</p><div class="requests-table-wrap"><table class="requests-table"><thead><tr><th scope="col">Solicitud</th><th scope="col">Cliente</th><th scope="col">Productos</th><th scope="col">Total</th><th scope="col">Solicitud</th><th scope="col">Pago</th><th scope="col"><span class="visually-hidden">Acción</span></th></tr></thead><tbody>${requests.map(row).join('')}</tbody></table></div><ul class="requests-cards">${requests.map(card).join('')}</ul></section>`;
}

export function purchaseRequestDetailView(request, { values = {}, operation = '', dirty = false, quantityErrors = {} } = {}) {
  const busy = Boolean(operation);
  const saving = operation === 'saving';
  const verifyingPayment = operation === 'verifyingPayment';
  const rejectingPayment = operation === 'rejectingPayment';
  const editable = request.estado === 'nueva';
  const payment = paymentFor(request) || { estado: 'pendiente' };
  const hasPendingProof = payment.estado === 'comprobante_enviado';
  const customerEditable = editable && payment.estado !== 'verificado';
  const lineEditable = editable && !['comprobante_enviado', 'verificado'].includes(payment.estado);
  const formValues = { nombre_cliente: request.nombre_cliente, telefono: request.telefono, ciudad: request.ciudad || '', observaciones: request.observaciones || '', lineas: request.detalles_solicitud || [], ...values };
  const customerActions = customerEditable ? `<div class="request-form__actions request-customer-edit-actions" data-request-edit-actions ${dirty ? '' : 'hidden'}><button class="secondary-button" type="button" data-request-discard ${busy ? 'disabled' : ''}>Descartar cambios</button><button class="primary-button" type="submit" data-request-save data-busy-label="Guardando..." ${busy ? `disabled${saving ? ' aria-busy="true"' : ''}` : ''}>${saving ? 'Guardando...' : 'Guardar cambios'}</button></div>` : '';
  const customer = customerEditable ? `<div class="request-form__fields"><label>Nombre<input name="nombre_cliente" required minlength="2" maxlength="100" value="${escapeHtml(formValues.nombre_cliente)}"></label><label>Teléfono<input name="telefono" required minlength="7" maxlength="20" value="${escapeHtml(formValues.telefono)}"></label><label class="request-form__city">Ciudad <span class="field-optional">· Opcional</span><input name="ciudad" maxlength="100" value="${escapeHtml(formValues.ciudad)}"></label><label class="request-form__observations">Observaciones <span class="field-optional">· Opcional</span><textarea name="observaciones" maxlength="500" rows="3">${escapeHtml(formValues.observaciones)}</textarea></label></div>${hasPendingProof ? '<p class="request-customer-payment-note">Puedes corregir los datos del cliente antes de aprobar el pago. Para modificar productos o cantidades debes rechazar primero el comprobante.</p>' : ''}${customerActions}` : `<dl class="request-customer"><div><dt>Nombre</dt><dd>${escapeHtml(request.nombre_cliente)}</dd></div><div><dt>Teléfono</dt><dd>${escapeHtml(request.telefono)}</dd></div><div><dt>Ciudad</dt><dd>${escapeHtml(request.ciudad || '—')}</dd></div><div class="request-customer__observations"><dt>Observaciones</dt><dd>${escapeHtml(request.observaciones || '—')}</dd></div></dl>`;
  const lines = editable ? formValues.lineas : request.detalles_solicitud || [];
  const transitionDisabled = busy || dirty;
  const paymentReviewActions = editable && hasPendingProof ? `<div class="payment-review-actions"><button class="request-confirm-button" type="button" data-payment-verify ${busy || dirty ? `disabled${verifyingPayment ? ' aria-busy="true"' : ''}` : ''}>${checkIcon}<span>${verifyingPayment ? 'Procesando...' : 'Aprobar pago y confirmar solicitud'}</span></button><button class="secondary-button payment-reject-button" type="button" data-payment-reject ${busy ? `disabled${rejectingPayment ? ' aria-busy="true"' : ''}` : ''}>${closeIcon}<span>${rejectingPayment ? 'Rechazando...' : 'Rechazar comprobante'}</span></button></div>` : '';
  const paymentReviewNotice = hasPendingProof ? `<p class="payment-approval-notice">${infoIcon}<span><strong>Al aprobar el pago, la solicitud se confirmará y quedará en solo lectura.</strong><small>Revisa el comprobante y cualquier dato pendiente antes de continuar.</small></span></p><p class="request-action-hint payment-review-dirty-hint" data-payment-dirty-hint ${dirty ? '' : 'hidden'}>${infoIcon}<span>Guarda o descarta los cambios antes de confirmar la solicitud.</span></p>` : '';
  const stateAction = request.estado === 'nueva' && !hasPendingProof
    ? `<button class="request-confirm-button" type="button" data-request-transition="confirm" ${transitionDisabled ? `disabled${operation === 'confirm' ? ' aria-busy="true"' : ''}` : ''}>${operation === 'confirm' ? 'Procesando...' : 'Confirmar solicitud'}</button>`
    : request.estado === 'confirmada'
      ? `<button class="primary-button" type="button" data-request-transition="deliver" ${transitionDisabled ? `disabled${operation === 'deliver' ? ' aria-busy="true"' : ''}` : ''}>${operation === 'deliver' ? 'Procesando...' : 'Marcar como entregada'}</button>`
      : '';
  const cancelAction = ['nueva', 'confirmada'].includes(request.estado) ? `<button class="danger-button" type="button" data-request-transition="cancel" ${transitionDisabled ? `disabled${operation === 'cancel' ? ' aria-busy="true"' : ''}` : ''}>${operation === 'cancel' ? 'Cancelando...' : 'Cancelar solicitud'}</button>` : '';
  const stateActions = stateAction ? `<section class="request-state-actions"><div><h3>Acciones de la solicitud</h3><p>${request.estado === 'nueva' ? 'Confirma esta solicitud cuando no existan cambios pendientes.' : 'Selecciona una acción válida para esta solicitud.'}</p><p class="request-action-hint" data-request-dirty-hint ${dirty ? '' : 'hidden'}>${infoIcon}<span>Guarda o descarta los cambios para continuar.</span></p></div><div class="request-form__actions">${stateAction}</div></section>` : '';
  const otherActions = cancelAction ? `<section class="request-other-actions"><div><h3>Otras acciones</h3><p>Cancelar finaliza esta solicitud y no forma parte de la revisión del comprobante.</p></div><div class="request-form__actions">${cancelAction}</div></section>` : '';
  const paymentMethod = payment.metodo === 'externo' ? 'Validación externa' : 'Bre-B';
  const paymentSection = `<section class="payment-admin-section${hasPendingProof ? ' payment-admin-section--pending' : ''}"><div class="payment-admin-section__heading"><h3>Pago</h3>${paymentDetailStatusView(payment)}</div>${hasPendingProof ? '<span class="payment-admin-section__review-state">Pendiente de revisión</span>' : ''}<div class="payment-admin-section__meta"><span><span class="visually-hidden">Método: </span>${paymentMethod}</span><strong><span class="visually-hidden">Monto: </span>${money(payment.monto || requestTotal(request))}</strong>${payment.enviado_en ? `<span class="payment-admin-section__sent">Enviado ${dateTime(payment.enviado_en)}</span>` : ''}</div>${payment.comprobante_path ? `<button class="payment-proof-open" type="button" data-payment-proof-open aria-label="Ver comprobante de pago" title="Ver comprobante">${eyeIcon}<span>Ver comprobante</span></button>` : `<p class="field-help">${payment.estado === 'validado_manualmente' ? 'La solicitud fue confirmada por el administrador sin comprobante en la plataforma.' : 'Todavía no se ha enviado comprobante.'}</p>`}${payment.observacion_revision ? `<p class="payment-admin-section__review-note"><strong>Observación de revisión:</strong> ${escapeHtml(payment.observacion_revision)}</p>` : ''}${paymentReviewNotice}${paymentReviewActions}</section>`;
  const detailContent = editable ? `<form id="request-edit-form" class="request-form">${!hasPendingProof && customerEditable ? `<p class="request-info">${infoIcon}<span>Esta solicitud aún no descuenta inventario. Puedes editar los datos y productos antes de confirmarla.</span></p>` : ''}<section class="request-section" aria-labelledby="request-customer-title"><h3 id="request-customer-title">Datos del cliente</h3>${customer}</section><section class="request-section" aria-labelledby="request-products-title"><h3 id="request-products-title">Productos solicitados</h3>${lineListView(lines, lineEditable, quantityErrors)}</section>${requestSummaryView({ ...request, detalles_solicitud: lines.map((line) => ({ ...line, cantidad: Number(line.cantidad), subtotal: Number(line.cantidad) * Number(line.precio_unitario) })) })}${paymentSection}<section class="request-action-groups">${stateActions}${otherActions}</section></form>` : `<section class="request-readonly"><section class="request-section" aria-labelledby="request-customer-title"><h3 id="request-customer-title">Datos del cliente</h3>${customer}</section><section class="request-section" aria-labelledby="request-products-title"><h3 id="request-products-title">Productos solicitados</h3>${lineListView(lines)}</section>${requestSummaryView(request)}${paymentSection}${stateActions}${otherActions}<p class="message message--info">Las solicitudes ${requestStatus(request.estado)} son de solo lectura.</p></section>`;
  return `<section class="request-detail"><button class="request-back-link" type="button" data-request-back>${backIcon}<span>Volver a solicitudes</span></button><header class="request-detail__heading"><div><h2>${escapeHtml(request.codigo)}</h2><p>${dateTime(request.creado_en)}</p></div>${statusView(request.estado)}</header>${detailContent}</section>`;
}
